import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Providers from "../context/providers";
import Navbar from '../components/navbar'
import Footer from '../components/footer'

import "./globals.css";
import "react-vertical-timeline-component/style.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
